mocha.server.port: 8026

spring.main.web-environment: false

spring.h2.console.enabled: true
spring.h2.console.path: /h2

spring.datasource.url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username: sa
spring.datasource.password:
spring.datasource.driver-class-name: org.h2.Driver

spring.jpa.hibernate.ddl-auto: update